apiVersion: v1                 # Kubernetes core API version
kind: Secret                   # Resource type = Secret

metadata:
  name: db-secret              # Secret resource name
  namespace: dev               # Secret belongs to dev namespace

type: Opaque                   # Generic key-value secret type

stringData:                    # Plain text secret values section
  DB_USERNAME: "admin"           # Username secret
  DB_PASSWORD: "mysecret123"     # Password secret

# kubectl apply -f secret.yml